const defaultSectionFooter = '\n---\n*Generated by FRAI - Responsible AI in Minutes*';

const ensureTips = (tips) =>
  tips && tips.trim().length > 0 ? tips.trim() : 'No specific tips available for this section.';

export const defaultChecklistTemplate = (context, tips) => {
  const { summaries } = context;
  return `# Responsible AI Feature Checklist

${summaries.checklist}

## Implementation Checklist

### Data & Privacy
- [ ] Data collection consent properly obtained and documented
- [ ] Data storage and access controls implemented
- [ ] Data retention and deletion policies defined
- [ ] Privacy impact assessment completed (if required)

### Model Development
- [ ] Training data quality and bias assessment completed
- [ ] Model validation and testing performed
- [ ] Performance benchmarks established
- [ ] Model limitations and assumptions documented

### Deployment & Monitoring
- [ ] Production monitoring and alerting configured
- [ ] Rollback procedures defined
- [ ] Performance degradation detection implemented
- [ ] User feedback collection mechanism established

### Governance & Compliance
- [ ] Stakeholder approval obtained
- [ ] Regulatory compliance verified
- [ ] Documentation review completed
- [ ] Incident response plan prepared

## AI-Powered Recommendations

${ensureTips(tips)}${defaultSectionFooter}`;
};

export const defaultModelCardTemplate = (context, tips) => {
  const { summaries, helpers, answers } = context;
  const { getPurposeDescription, getDataSourceDescription, getMetricDescription, getBiasDescription, getDataProtectionDescription, getMonitoringDescription } = helpers;

  return `# Model Card

${summaries.modelCard}

## Intended Use
- **Primary Use Cases**: ${getPurposeDescription(answers.core.purpose)}
- **Out-of-scope Uses**: To be defined based on specific implementation

## Training Data
- **Data Sources**: ${
    answers.data.dataSource
      ? getDataSourceDescription(answers.data.dataSource)
      : 'See data section above'
  }
- **Data Preprocessing**: Standard preprocessing applied
- **Data Limitations**: ${
    answers.core.dataType === 'sensitive'
      ? 'Sensitive data requires careful handling'
      : 'Standard data limitations apply'
  }

## Evaluation
- **Primary Metric**: ${getMetricDescription(answers.performance.primaryMetric)}
- **Performance**: To be measured in production
- **Bias Testing**: ${getBiasDescription(answers.bias.biasConsiderations)}

## Ethical Considerations
- **Bias & Fairness**: ${getBiasDescription(answers.bias.biasConsiderations)}
- **Privacy**: ${
    answers.data.dataProtection
      ? getDataProtectionDescription(answers.data.dataProtection)
      : 'Standard privacy measures'
  }
- **Transparency**: Model decisions should be explainable where possible

## Monitoring & Maintenance
- **Monitoring Strategy**: ${getMonitoringDescription(answers.monitoring.monitoring)}
- **Update Frequency**: To be determined based on performance
- **Version Control**: Standard ML model versioning practices

## AI-Powered Recommendations

${ensureTips(tips)}${defaultSectionFooter}`;
};

export const defaultRiskFileTemplate = (context, tips) => {
  const { summaries, answers, helpers } = context;
  const { getDataProtectionDescription } = helpers;

  return `# AI Model Risk & Compliance

${summaries.risk}

## Risk Mitigation Strategies

### Technical Risks
- **Model Performance**: Regular performance monitoring and validation
- **Data Quality**: Continuous data quality checks and validation
- **Security**: Secure model deployment and access controls
- **Scalability**: Performance testing under various load conditions

### Operational Risks
- **Human Oversight**: ${
    answers.impact?.automationImpact === 'autonomous'
      ? 'Critical - implement human oversight'
      : 'Implement appropriate human oversight'
  }
- **Process Integration**: Ensure smooth integration with existing workflows
- **Training & Documentation**: Adequate training for operators and users
- **Incident Response**: Clear procedures for handling model failures

### Regulatory & Compliance
- **Data Protection**: ${
    answers.data.dataProtection
      ? getDataProtectionDescription(answers.data.dataProtection)
      : 'Standard compliance measures'
  }
- **Industry Standards**: Compliance with relevant industry standards
- **Audit Trail**: Comprehensive logging and audit capabilities
- **Documentation**: Complete documentation for regulatory review

## Monitoring & Alerting

### Key Metrics to Monitor
- Model performance metrics
- Data quality indicators
- System performance and availability
- User satisfaction and feedback

### Alert Thresholds
- Performance degradation beyond acceptable limits
- Data quality issues or anomalies
- System failures or errors
- Unusual usage patterns

## AI-Powered Recommendations

${ensureTips(tips)}${defaultSectionFooter}`;
};
